language: c
matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx
script: 
  - ./install.sh
  - python --version
  - ./epa_trainer.py
  - ./epa_classifier.py
  - ./test.sh
